# Generated by Django 5.0.6 on 2024-05-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_administrator',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('atrasado', 'Atrasado'), ('filial', 'Filial')], default='regular', max_length=20),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
