# Generated by Django 5.0.6 on 2024-05-31 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0006_alter_listadistribuida_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadistribuida',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
