# Generated by Django 5.0.6 on 2024-05-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0008_alter_listadistribuida_tipo_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadistribuida',
            name='data_distribuicao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
