# Generated by Django 5.0.6 on 2024-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0011_interacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadistribuida',
            name='lista',
            field=models.TextField(blank=True, null=True),
        ),
    ]
