# Generated by Django 5.0.6 on 2024-06-03 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0012_listadistribuida_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadistribuida',
            name='id_lista',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
