# Generated by Django 5.0.6 on 2024-06-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0013_listadistribuida_id_lista'),
    ]

    operations = [
        migrations.AddField(
            model_name='interacao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
