# Generated by Django 5.0.6 on 2024-06-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0014_interacao_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacao',
            name='lista_distribuida',
        ),
        migrations.AddField(
            model_name='interacao',
            name='lista_distribuida_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
