# Generated by Django 5.0.6 on 2024-06-03 14:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0015_remove_interacao_lista_distribuida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interacao',
            name='lista_distribuida_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
