# Generated by Django 5.0.6 on 2024-06-03 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0018_caderno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caderno',
            name='observacao',
        ),
    ]
