# Generated by Django 5.0.6 on 2024-06-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0019_remove_caderno_observacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoTransferido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20)),
                ('nome_titular', models.CharField(max_length=255)),
                ('data_pgto', models.DateField()),
                ('parcela', models.CharField(max_length=7)),
            ],
        ),
    ]
