# Generated by Django 5.0.6 on 2024-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0020_pagamentotransferido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentotransferido',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagamentotransferido',
            name='nome_titular',
            field=models.CharField(max_length=100),
        ),
    ]
