# Generated by Django 5.0.6 on 2024-06-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0021_pagamentotransferido_criado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentotransferido',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
