# Generated by Django 5.0.6 on 2024-06-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0023_pagamentoremovido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoremovido',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
