# Generated by Django 5.0.6 on 2024-06-10 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0024_pagamentoremovido_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoremovido',
            name='colaborador_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_transferidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pagamentoremovido',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos_removidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
