# Generated by Django 5.0.6 on 2024-06-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0025_pagamentoremovido_colaborador_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoremovido',
            name='parcela',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
