# Generated by Django 5.0.6 on 2024-06-13 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0026_pagamentoremovido_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialConvalescente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=20)),
                ('data_pagamento', models.DateField()),
                ('material', models.CharField(max_length=100)),
                ('parcelas', models.CharField(max_length=7)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
