# Generated by Django 5.0.6 on 2024-06-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0027_materialconvalescente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialconvalescente',
            name='colaborador',
        ),
        migrations.RemoveField(
            model_name='materialconvalescente',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='materialconvalescente',
            name='codigo_cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='materialconvalescente',
            name='parcelas',
            field=models.TextField(),
        ),
    ]
