# Generated by Django 5.0.6 on 2024-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0029_materialconvalescente_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialconvalescente',
            name='parcelas',
            field=models.IntegerField(),
        ),
    ]
